import React, { createContext, useContext, useState } from 'react';

const PatientContext = createContext();

export const PatientProvider = ({ children }) => {
  const [patients, setPatients] = useState([
    {
      id: 1,
      patientId: "P001",
      patientLastName: "Smith",
      patientFirstName: "John",
      patientMiddleName: "A",
      patientDOB: "05-15-1980",
      contactNumber: "555-123-4567",
      physicianName: "Dr. Sarah Johnson",
      pg: "PG Alpha",
      hhah: "Home Health Care Plus",
      patientInsurance: "Medicare",
      patientInEHR: "yes",
      patientSOC: "08-30-2024",
      patientEpisodeFrom: "08-30-2024",
      patientEpisodeTo: "10-28-2024",
      renderingPractitioner: "Dr. Michael Chen",
      primaryDiagnosisCodes: ["E11.9", "I10"],
      secondaryDiagnosisCodes: ["M17.9", "E78.5"],
      certStatus: "Document Signed",
      certSignedDate: "09-15-2024",
      recertStatus: "Document Prepared",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Regular follow-up required",
      cpoMinsCaptured: 120,
      newDocs: 7,
      newCpoDocsCreated: 2,
      billingCode: "179",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 2,
      patientId: "P002",
      patientLastName: "Johnson",
      patientFirstName: "Emily",
      patientMiddleName: "R",
      patientDOB: "07-22-1975",
      contactNumber: "555-234-5678",
      physicianName: "Dr. Robert Williams",
      pg: "PG Beta",
      hhah: "Golden Age Home Health",
      patientInsurance: "BlueCross",
      patientInEHR: "yes",
      patientSOC: "08-14-2024",
      patientEpisodeFrom: "08-14-2024",
      patientEpisodeTo: "10-12-2024",
      renderingPractitioner: "Dr. Lisa Park",
      primaryDiagnosisCodes: ["I48.91", "E78.5"],
      secondaryDiagnosisCodes: ["J44.9", "N18.3"],
      certStatus: "Document Signed",
      certSignedDate: "08-25-2024",
      recertStatus: "Document not received",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Patient has mobility issues",
      cpoMinsCaptured: 95,
      newDocs: 8,
      newCpoDocsCreated: 3,
      billingCode: "180",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 3,
      patientId: "P003",
      patientLastName: "Williams",
      patientFirstName: "Michael",
      patientMiddleName: "T",
      patientDOB: "03-10-1968",
      contactNumber: "555-345-6789",
      physicianName: "Dr. Jennifer Lee",
      pg: "PG Gamma",
      hhah: "Comfort Care Services",
      patientInsurance: "Aetna",
      patientInEHR: "yes",
      patientSOC: "09-01-2024",
      patientEpisodeFrom: "09-01-2024",
      patientEpisodeTo: "11-30-2024",
      renderingPractitioner: "Dr. David Kim",
      primaryDiagnosisCodes: ["I25.10", "E11.65"],
      secondaryDiagnosisCodes: ["I10", "M17.9"],
      certStatus: "Document Prepared",
      certSignedDate: "",
      recertStatus: "Not applicable",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Cardiac monitoring required",
      cpoMinsCaptured: 150,
      newDocs: 5,
      newCpoDocsCreated: 1,
      billingCode: "181",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 4,
      patientId: "P004",
      patientLastName: "Brown",
      patientFirstName: "Patricia",
      patientMiddleName: "L",
      patientDOB: "11-28-1955",
      contactNumber: "555-456-7890",
      physicianName: "Dr. James Wilson",
      pg: "PG Delta",
      hhah: "Elite Home Health",
      patientInsurance: "UnitedHealthcare",
      patientInEHR: "yes",
      patientSOC: "08-20-2024",
      patientEpisodeFrom: "08-20-2024",
      patientEpisodeTo: "10-19-2024",
      renderingPractitioner: "Dr. Susan Martinez",
      primaryDiagnosisCodes: ["J45.909", "E78.5"],
      secondaryDiagnosisCodes: ["I10", "M54.2"],
      certStatus: "Document Signed",
      certSignedDate: "08-25-2024",
      recertStatus: "Document Prepared",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Asthma management",
      cpoMinsCaptured: 85,
      newDocs: 6,
      newCpoDocsCreated: 2,
      billingCode: "179",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 5,
      patientId: "P005",
      patientLastName: "Davis",
      patientFirstName: "Robert",
      patientMiddleName: "K",
      patientDOB: "09-15-1948",
      contactNumber: "555-567-8901",
      physicianName: "Dr. Thomas Anderson",
      pg: "PG Epsilon",
      hhah: "Senior Care Solutions",
      patientInsurance: "Cigna",
      patientInEHR: "yes",
      patientSOC: "09-05-2024",
      patientEpisodeFrom: "09-05-2024",
      patientEpisodeTo: "11-04-2024",
      renderingPractitioner: "Dr. Maria Garcia",
      primaryDiagnosisCodes: ["G20", "I10"],
      secondaryDiagnosisCodes: ["E11.9", "M54.5"],
      certStatus: "Document Signed",
      certSignedDate: "09-10-2024",
      recertStatus: "Not applicable",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Parkinson's management",
      cpoMinsCaptured: 110,
      newDocs: 4,
      newCpoDocsCreated: 1,
      billingCode: "180",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 6,
      patientId: "P006",
      patientLastName: "Miller",
      patientFirstName: "Jennifer",
      patientMiddleName: "M",
      patientDOB: "04-22-1972",
      contactNumber: "555-678-9012",
      physicianName: "Dr. Richard Taylor",
      pg: "PG Alpha",
      hhah: "CareFirst Home Health",
      patientInsurance: "Medicare",
      patientInEHR: "yes",
      patientSOC: "08-25-2024",
      patientEpisodeFrom: "08-25-2024",
      patientEpisodeTo: "10-24-2024",
      renderingPractitioner: "Dr. Kevin White",
      primaryDiagnosisCodes: ["E11.9", "I10"],
      secondaryDiagnosisCodes: ["M17.9", "E78.5"],
      certStatus: "Document Prepared",
      certSignedDate: "",
      recertStatus: "Not applicable",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Diabetes management",
      cpoMinsCaptured: 95,
      newDocs: 3,
      newCpoDocsCreated: 1,
      billingCode: "179",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 7,
      patientId: "P007",
      patientLastName: "Wilson",
      patientFirstName: "David",
      patientMiddleName: "P",
      patientDOB: "12-05-1960",
      contactNumber: "555-789-0123",
      physicianName: "Dr. Elizabeth Brown",
      pg: "PG Beta",
      hhah: "HealthCare Plus",
      patientInsurance: "BlueCross",
      patientInEHR: "yes",
      patientSOC: "09-10-2024",
      patientEpisodeFrom: "09-10-2024",
      patientEpisodeTo: "11-09-2024",
      renderingPractitioner: "Dr. Christopher Lee",
      primaryDiagnosisCodes: ["I25.10", "E78.5"],
      secondaryDiagnosisCodes: ["I10", "J45.909"],
      certStatus: "Document Signed",
      certSignedDate: "09-15-2024",
      recertStatus: "Document Prepared",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Cardiac rehabilitation",
      cpoMinsCaptured: 130,
      newDocs: 5,
      newCpoDocsCreated: 2,
      billingCode: "180",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 8,
      patientId: "P008",
      patientLastName: "Moore",
      patientFirstName: "Sarah",
      patientMiddleName: "J",
      patientDOB: "06-18-1978",
      contactNumber: "555-890-1234",
      physicianName: "Dr. Patricia Davis",
      pg: "PG Gamma",
      hhah: "Comfort Care Services",
      patientInsurance: "Aetna",
      patientInEHR: "yes",
      patientSOC: "08-15-2024",
      patientEpisodeFrom: "08-15-2024",
      patientEpisodeTo: "10-14-2024",
      renderingPractitioner: "Dr. Daniel Wilson",
      primaryDiagnosisCodes: ["M17.9", "E11.9"],
      secondaryDiagnosisCodes: ["I10", "E78.5"],
      certStatus: "Document Signed",
      certSignedDate: "08-20-2024",
      recertStatus: "Not applicable",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Knee replacement recovery",
      cpoMinsCaptured: 75,
      newDocs: 4,
      newCpoDocsCreated: 1,
      billingCode: "181",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 9,
      patientId: "P009",
      patientLastName: "Taylor",
      patientFirstName: "James",
      patientMiddleName: "R",
      patientDOB: "02-14-1952",
      contactNumber: "555-901-2345",
      physicianName: "Dr. Michael Johnson",
      pg: "PG Delta",
      hhah: "Elite Home Health",
      patientInsurance: "UnitedHealthcare",
      patientInEHR: "yes",
      patientSOC: "09-20-2024",
      patientEpisodeFrom: "09-20-2024",
      patientEpisodeTo: "11-19-2024",
      renderingPractitioner: "Dr. Lisa Anderson",
      primaryDiagnosisCodes: ["I48.91", "I10"],
      secondaryDiagnosisCodes: ["E78.5", "M54.2"],
      certStatus: "Document Prepared",
      certSignedDate: "",
      recertStatus: "Not applicable",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Atrial fibrillation monitoring",
      cpoMinsCaptured: 100,
      newDocs: 6,
      newCpoDocsCreated: 2,
      billingCode: "179",
      charges: 113,
      pos: "11",
      units: 1
    },
    // Validation test patients - specifically designed for Jan/Feb/Mar 2024 billing windows
    // JANUARY 2024 VALIDATION PATIENTS
    {
      id: 101,
      patientId: "VT001",
      patientFirstName: "John",
      patientMiddleName: "",
      patientLastName: "Doe",
      patientDOB: "05/15/1965",
      patientGender: "Male",
      patientAddress: "123 Main St, Phoenix, AZ",
      patientPhone: "(480) 555-1234",
      patientEmail: "john.doe@email.com",
      patientInsurance: "Medicare",
      patientSOC: "01/05/2024",
      patientEpisodeFrom: "01/05/2024",
      patientEpisodeTo: "07/05/2024",
      primaryDiagnosisCodes: ["I10", "E11.9"],
      secondaryDiagnosisCodes: ["M19.90", "I50.9"],
      hhah: "HomeHealth Plus",
      physicianName: "Dr. Sarah Johnson",
      physicianId: 1,
      billingCode: "G0180", // Initial certification
      charges: 85,
      pos: "11",
      units: 1,
      pg: "pg-alpha",
      patientRemarks: "CERT - January 2024 billing window",
      cpoMinsCaptured: 15,
      certStatus: "Document Signed",
      recertStatus: "Not applicable", 
      certSignedDate: "01/15/2024",
      recertSignedDate: "",
      contactNumber: "555-123-4567",
      renderingPractitioner: "Dr. Sarah Johnson",
      f2fEligibility: "yes",
      newDocs: 3,
      newCpoDocsCreated: 1,
      patientInEHR: "yes"
    },
    {
      id: 102,
      patientId: "VT002",
      patientFirstName: "Jane",
      patientMiddleName: "Maria",
      patientLastName: "Smith",
      patientDOB: "08/23/1972",
      patientGender: "Female",
      patientAddress: "456 Oak Ave, Scottsdale, AZ",
      patientPhone: "(480) 555-5678",
      patientEmail: "jane.smith@email.com",
      patientInsurance: "Blue Cross",
      patientSOC: "07/05/2023",
      patientEpisodeFrom: "01/05/2024",
      patientEpisodeTo: "07/05/2024",
      primaryDiagnosisCodes: ["I48.91"],
      secondaryDiagnosisCodes: ["E78.5", "N18.3"],
      hhah: "CaringHands HHA",
      physicianName: "Dr. Robert Chen",
      physicianId: 2,
      billingCode: "G0179", // Recertification
      charges: 75,
      pos: "11",
      units: 1,
      pg: "pg-alpha",
      patientRemarks: "RECERT - January 2024 billing window",
      cpoMinsCaptured: 20,
      certStatus: "Document Signed",
      recertStatus: "Document Signed", 
      certSignedDate: "07/10/2023",
      recertSignedDate: "01/10/2024",
      contactNumber: "555-234-5678",
      renderingPractitioner: "Dr. Robert Chen",
      f2fEligibility: "yes",
      newDocs: 4,
      newCpoDocsCreated: 1,
      patientInEHR: "yes"
    },
    {
      id: 103,
      patientId: "VT003",
      patientFirstName: "Robert",
      patientMiddleName: "",
      patientLastName: "Johnson",
      patientDOB: "03/12/1958",
      patientGender: "Male",
      patientAddress: "789 Pine Rd, Tempe, AZ",
      patientPhone: "(480) 555-9012",
      patientEmail: "robert.johnson@email.com",
      patientInsurance: "Aetna",
      patientSOC: "11/20/2023",
      patientEpisodeFrom: "11/20/2023",
      patientEpisodeTo: "05/20/2024",
      primaryDiagnosisCodes: ["I25.10", "I21.4"],
      secondaryDiagnosisCodes: ["I10", "E11.9"],
      hhah: "Comfort Care Services",
      physicianName: "Dr. Maria Garcia",
      physicianId: 3,
      billingCode: "G0181", // Care Plan Oversight
      charges: 113,
      pos: "11",
      units: 1,
      pg: "pg-alpha",
      patientRemarks: "CPO - January 2024 billing window",
      cpoMinsCaptured: 45, // Enough for CPO
      certStatus: "Document Signed",
      recertStatus: "Document not received", 
      certSignedDate: "11/25/2023",
      recertSignedDate: "",
      contactNumber: "555-345-6789",
      renderingPractitioner: "Dr. Maria Garcia",
      f2fEligibility: "yes",
      newDocs: 5,
      newCpoDocsCreated: 2,
      patientInEHR: "yes"
    },
    
    // FEBRUARY 2024 VALIDATION PATIENTS
    {
      id: 104,
      patientId: "VT004",
      patientFirstName: "Mary",
      patientMiddleName: "Ann",
      patientLastName: "Williams",
      patientDOB: "11/30/1981",
      patientGender: "Female",
      patientAddress: "101 Cedar St, Mesa, AZ",
      patientPhone: "(480) 555-3456",
      patientEmail: "mary.williams@email.com",
      patientInsurance: "United Healthcare",
      patientSOC: "02/10/2024",
      patientEpisodeFrom: "02/10/2024",
      patientEpisodeTo: "08/10/2024",
      primaryDiagnosisCodes: ["G35"],
      secondaryDiagnosisCodes: ["F33.1", "M54.5"],
      hhah: "Elite Home Health",
      physicianName: "Dr. James Wilson",
      physicianId: 4,
      billingCode: "G0180", // Initial certification
      charges: 85,
      pos: "11",
      units: 1,
      pg: "pg-alpha",
      patientRemarks: "CERT - February 2024 billing window",
      cpoMinsCaptured: 15,
      certStatus: "Document Signed",
      recertStatus: "Not applicable", 
      certSignedDate: "02/15/2024",
      recertSignedDate: "",
      contactNumber: "555-456-7890",
      renderingPractitioner: "Dr. James Wilson",
      f2fEligibility: "yes",
      newDocs: 2,
      newCpoDocsCreated: 1,
      patientInEHR: "yes"
    },
    {
      id: 105,
      patientId: "VT005",
      patientFirstName: "David",
      patientMiddleName: "",
      patientLastName: "Brown",
      patientDOB: "07/08/1945",
      patientGender: "Male",
      patientAddress: "222 Maple Dr, Chandler, AZ",
      patientPhone: "(480) 555-7890",
      patientEmail: "david.brown@email.com",
      patientInsurance: "Medicare",
      patientSOC: "08/20/2023",
      patientEpisodeFrom: "02/20/2024",
      patientEpisodeTo: "08/20/2024",
      primaryDiagnosisCodes: ["I50.9"],
      secondaryDiagnosisCodes: ["N18.4", "E87.1"],
      hhah: "HomeHealth Plus",
      physicianName: "Dr. Emily Brown",
      physicianId: 5,
      billingCode: "G0179", // Recertification
      charges: 75,
      pos: "11",
      units: 1,
      pg: "pg-alpha",
      patientRemarks: "RECERT - February 2024 billing window",
      cpoMinsCaptured: 20,
      certStatus: "Document Signed",
      recertStatus: "Document Signed", 
      certSignedDate: "08/25/2023",
      recertSignedDate: "02/22/2024",
      contactNumber: "555-567-8901",
      renderingPractitioner: "Dr. Emily Brown",
      f2fEligibility: "yes",
      newDocs: 6,
      newCpoDocsCreated: 1,
      patientInEHR: "yes"
    },
    {
      id: 106,
      patientId: "VT006",
      patientFirstName: "Thomas",
      patientMiddleName: "J",
      patientLastName: "Miller",
      patientDOB: "09/14/1962",
      patientGender: "Male",
      patientAddress: "333 Elm Ct, Gilbert, AZ",
      patientPhone: "(480) 555-2345",
      patientEmail: "thomas.miller@email.com",
      patientInsurance: "Cigna",
      patientSOC: "10/05/2023",
      patientEpisodeFrom: "10/05/2023",
      patientEpisodeTo: "04/05/2024",
      primaryDiagnosisCodes: ["J44.9", "J96.00"],
      secondaryDiagnosisCodes: ["I10", "E78.5"],
      hhah: "Caring Hearts HHA",
      physicianName: "Dr. William Taylor",
      physicianId: 6,
      billingCode: "G0181", // Care Plan Oversight
      charges: 113,
      pos: "11",
      units: 1,
      pg: "pg-alpha",
      patientRemarks: "CPO - February 2024 billing window",
      cpoMinsCaptured: 50, // Enough for CPO
      certStatus: "Document Signed",
      recertStatus: "Not applicable", 
      certSignedDate: "10/10/2023",
      recertSignedDate: "",
      contactNumber: "555-678-9012",
      renderingPractitioner: "Dr. William Taylor",
      f2fEligibility: "yes",
      newDocs: 7,
      newCpoDocsCreated: 2,
      patientInEHR: "yes"
    },
    
    // MARCH 2024 VALIDATION PATIENTS
    {
      id: 107,
      patientId: "VT007",
      patientFirstName: "Elizabeth",
      patientMiddleName: "K",
      patientLastName: "Garcia",
      patientDOB: "04/02/1970",
      patientGender: "Female",
      patientAddress: "444 Birch Ln, Peoria, AZ",
      patientPhone: "(480) 555-6789",
      patientEmail: "elizabeth.garcia@email.com",
      patientInsurance: "Medicare Advantage",
      patientSOC: "03/08/2024",
      patientEpisodeFrom: "03/08/2024",
      patientEpisodeTo: "09/08/2024",
      primaryDiagnosisCodes: ["C50.911", "Z85.3"],
      secondaryDiagnosisCodes: ["D64.9", "R53.83"],
      hhah: "Phoenix Home Health",
      physicianName: "Dr. Jennifer Lopez",
      physicianId: 7,
      billingCode: "G0180", // Initial certification
      charges: 85,
      pos: "11",
      units: 1,
      pg: "pg-alpha",
      patientRemarks: "CERT - March 2024 billing window",
      cpoMinsCaptured: 15,
      certStatus: "Document Signed",
      recertStatus: "Not applicable", 
      certSignedDate: "03/15/2024",
      recertSignedDate: "",
      contactNumber: "555-890-1234",
      renderingPractitioner: "Dr. Jennifer Lopez",
      f2fEligibility: "yes",
      newDocs: 4,
      newCpoDocsCreated: 1,
      patientInEHR: "yes"
    },
    {
      id: 108,
      patientId: "VT008",
      patientFirstName: "Richard",
      patientMiddleName: "L",
      patientLastName: "Martinez",
      patientDOB: "06/15/1950",
      patientGender: "Male",
      patientAddress: "555 Spruce Dr, Glendale, AZ",
      patientPhone: "(480) 555-4567",
      patientEmail: "richard.martinez@email.com",
      patientInsurance: "Medicare",
      patientSOC: "09/10/2023",
      patientEpisodeFrom: "03/10/2024",
      patientEpisodeTo: "09/10/2024",
      primaryDiagnosisCodes: ["I63.9", "I69.30"],
      secondaryDiagnosisCodes: ["I10", "E11.9"],
      hhah: "Valley Home Health",
      physicianName: "Dr. Mark Rodriguez",
      physicianId: 8,
      billingCode: "G0179", // Recertification
      charges: 75,
      pos: "11",
      units: 1,
      pg: "pg-alpha",
      patientRemarks: "RECERT - March 2024 billing window",
      cpoMinsCaptured: 20,
      certStatus: "Document Signed",
      recertStatus: "Document Signed", 
      certSignedDate: "09/15/2023",
      recertSignedDate: "03/12/2024",
      contactNumber: "555-901-2345",
      renderingPractitioner: "Dr. Mark Rodriguez",
      f2fEligibility: "yes",
      newDocs: 5,
      newCpoDocsCreated: 1,
      patientInEHR: "yes"
    },
    {
      id: 109,
      patientId: "VT009",
      patientFirstName: "Susan",
      patientMiddleName: "A",
      patientLastName: "Thompson",
      patientDOB: "10/28/1975",
      patientGender: "Female",
      patientAddress: "666 Aspen Way, Surprise, AZ",
      patientPhone: "(480) 555-8901",
      patientEmail: "susan.thompson@email.com",
      patientInsurance: "Blue Cross",
      patientSOC: "12/15/2023",
      patientEpisodeFrom: "12/15/2023",
      patientEpisodeTo: "06/15/2024",
      primaryDiagnosisCodes: ["M15.0", "M79.7"],
      secondaryDiagnosisCodes: ["G89.29", "F41.1"],
      hhah: "Caring Hands HHA",
      physicianName: "Dr. Patricia Wright",
      physicianId: 9,
      billingCode: "G0181", // Care Plan Oversight
      charges: 113,
      pos: "11",
      units: 1,
      pg: "pg-alpha",
      patientRemarks: "CPO - March 2024 billing window",
      cpoMinsCaptured: 55, // Enough for CPO
      certStatus: "Document Signed",
      recertStatus: "Document not received", 
      certSignedDate: "12/20/2023",
      recertSignedDate: "",
      contactNumber: "555-123-7890",
      renderingPractitioner: "Dr. Patricia Wright",
      f2fEligibility: "yes",
      newDocs: 8,
      newCpoDocsCreated: 3,
      patientInEHR: "yes"
    }
  ]);

  const addPatient = (newPatient) => {
    setPatients(prevPatients => [...prevPatients, { ...newPatient, id: prevPatients.length + 1 }]);
  };

  const getPatientsByPG = (pgName) => {
    console.log(`Getting patients for PG: "${pgName}"`);
    
    // Normalize all patient PG names for consistent comparison
    const filteredPatients = patients.filter(patient => {
      const normalizedPatientPG = patient.pg ? patient.pg.toLowerCase() : '';
      console.log(`Checking patient ${patient.patientId}, PG: "${normalizedPatientPG}" against "${pgName}"`);
      return normalizedPatientPG === pgName;
    });
    
    console.log(`Found ${filteredPatients.length} patients for PG: ${pgName}`);
    return filteredPatients;
  };

  return (
    <PatientContext.Provider value={{ patients, addPatient, getPatientsByPG }}>
      {children}
    </PatientContext.Provider>
  );
};

export const usePatientContext = () => {
  const context = useContext(PatientContext);
  if (!context) {
    throw new Error('usePatientContext must be used within a PatientProvider');
  }
  return context;
}; 