import React, { createContext, useContext, useState } from 'react';

const PatientContext = createContext();

export const PatientProvider = ({ children }) => {
  const [patients, setPatients] = useState([
    {
      id: 1,
      patientId: "P001",
      patientLastName: "Smith",
      patientFirstName: "John",
      patientMiddleName: "A",
      patientDOB: "05-15-1980",
      contactNumber: "555-123-4567",
      physicianName: "Dr. Sarah Johnson",
      pg: "PG Alpha",
      hhah: "Home Health Care Plus",
      patientInsurance: "Medicare",
      patientInEHR: "yes",
      patientSOC: "08-30-2024",
      patientEpisodeFrom: "08-30-2024",
      patientEpisodeTo: "10-28-2024",
      renderingPractitioner: "Dr. Michael Chen",
      primaryDiagnosisCodes: ["E11.9", "I10"],
      secondaryDiagnosisCodes: ["M17.9", "E78.5"],
      certStatus: "Document Signed",
      certSignedDate: "09-15-2024",
      recertStatus: "Document Prepared",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Regular follow-up required",
      cpoMinsCaptured: 120,
      newDocs: 7,
      newCpoDocsCreated: 2,
      billingCode: "179",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 2,
      patientId: "P002",
      patientLastName: "Johnson",
      patientFirstName: "Emily",
      patientMiddleName: "R",
      patientDOB: "07-22-1975",
      contactNumber: "555-234-5678",
      physicianName: "Dr. Robert Williams",
      pg: "PG Beta",
      hhah: "Golden Age Home Health",
      patientInsurance: "BlueCross",
      patientInEHR: "yes",
      patientSOC: "08-14-2024",
      patientEpisodeFrom: "08-14-2024",
      patientEpisodeTo: "10-12-2024",
      renderingPractitioner: "Dr. Lisa Park",
      primaryDiagnosisCodes: ["I48.91", "E78.5"],
      secondaryDiagnosisCodes: ["J44.9", "N18.3"],
      certStatus: "Document Signed",
      certSignedDate: "08-25-2024",
      recertStatus: "Document not received",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Patient has mobility issues",
      cpoMinsCaptured: 95,
      newDocs: 8,
      newCpoDocsCreated: 3,
      billingCode: "180",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 3,
      patientId: "P003",
      patientLastName: "Williams",
      patientFirstName: "Michael",
      patientMiddleName: "T",
      patientDOB: "03-10-1968",
      contactNumber: "555-345-6789",
      physicianName: "Dr. Jennifer Lee",
      pg: "PG Gamma",
      hhah: "Comfort Care Services",
      patientInsurance: "Aetna",
      patientInEHR: "yes",
      patientSOC: "09-01-2024",
      patientEpisodeFrom: "09-01-2024",
      patientEpisodeTo: "11-30-2024",
      renderingPractitioner: "Dr. David Kim",
      primaryDiagnosisCodes: ["I25.10", "E11.65"],
      secondaryDiagnosisCodes: ["I10", "M17.9"],
      certStatus: "Document Prepared",
      certSignedDate: "",
      recertStatus: "Not applicable",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Cardiac monitoring required",
      cpoMinsCaptured: 150,
      newDocs: 5,
      newCpoDocsCreated: 1,
      billingCode: "181",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 4,
      patientId: "P004",
      patientLastName: "Brown",
      patientFirstName: "Patricia",
      patientMiddleName: "L",
      patientDOB: "11-28-1955",
      contactNumber: "555-456-7890",
      physicianName: "Dr. James Wilson",
      pg: "PG Delta",
      hhah: "Elite Home Health",
      patientInsurance: "UnitedHealthcare",
      patientInEHR: "yes",
      patientSOC: "08-20-2024",
      patientEpisodeFrom: "08-20-2024",
      patientEpisodeTo: "10-19-2024",
      renderingPractitioner: "Dr. Susan Martinez",
      primaryDiagnosisCodes: ["J45.909", "E78.5"],
      secondaryDiagnosisCodes: ["I10", "M54.2"],
      certStatus: "Document Signed",
      certSignedDate: "08-25-2024",
      recertStatus: "Document Prepared",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Asthma management",
      cpoMinsCaptured: 85,
      newDocs: 6,
      newCpoDocsCreated: 2,
      billingCode: "179",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 5,
      patientId: "P005",
      patientLastName: "Davis",
      patientFirstName: "Robert",
      patientMiddleName: "K",
      patientDOB: "09-15-1948",
      contactNumber: "555-567-8901",
      physicianName: "Dr. Thomas Anderson",
      pg: "PG Epsilon",
      hhah: "Senior Care Solutions",
      patientInsurance: "Cigna",
      patientInEHR: "yes",
      patientSOC: "09-05-2024",
      patientEpisodeFrom: "09-05-2024",
      patientEpisodeTo: "11-04-2024",
      renderingPractitioner: "Dr. Maria Garcia",
      primaryDiagnosisCodes: ["G20", "I10"],
      secondaryDiagnosisCodes: ["E11.9", "M54.5"],
      certStatus: "Document Signed",
      certSignedDate: "09-10-2024",
      recertStatus: "Not applicable",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Parkinson's management",
      cpoMinsCaptured: 110,
      newDocs: 4,
      newCpoDocsCreated: 1,
      billingCode: "180",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 6,
      patientId: "P006",
      patientLastName: "Miller",
      patientFirstName: "Jennifer",
      patientMiddleName: "M",
      patientDOB: "04-22-1972",
      contactNumber: "555-678-9012",
      physicianName: "Dr. Richard Taylor",
      pg: "PG Alpha",
      hhah: "CareFirst Home Health",
      patientInsurance: "Medicare",
      patientInEHR: "yes",
      patientSOC: "08-25-2024",
      patientEpisodeFrom: "08-25-2024",
      patientEpisodeTo: "10-24-2024",
      renderingPractitioner: "Dr. Kevin White",
      primaryDiagnosisCodes: ["E11.9", "I10"],
      secondaryDiagnosisCodes: ["M17.9", "E78.5"],
      certStatus: "Document Prepared",
      certSignedDate: "",
      recertStatus: "Not applicable",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Diabetes management",
      cpoMinsCaptured: 95,
      newDocs: 3,
      newCpoDocsCreated: 1,
      billingCode: "179",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 7,
      patientId: "P007",
      patientLastName: "Wilson",
      patientFirstName: "David",
      patientMiddleName: "P",
      patientDOB: "12-05-1960",
      contactNumber: "555-789-0123",
      physicianName: "Dr. Elizabeth Brown",
      pg: "PG Beta",
      hhah: "HealthCare Plus",
      patientInsurance: "BlueCross",
      patientInEHR: "yes",
      patientSOC: "09-10-2024",
      patientEpisodeFrom: "09-10-2024",
      patientEpisodeTo: "11-09-2024",
      renderingPractitioner: "Dr. Christopher Lee",
      primaryDiagnosisCodes: ["I25.10", "E78.5"],
      secondaryDiagnosisCodes: ["I10", "J45.909"],
      certStatus: "Document Signed",
      certSignedDate: "09-15-2024",
      recertStatus: "Document Prepared",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Cardiac rehabilitation",
      cpoMinsCaptured: 130,
      newDocs: 5,
      newCpoDocsCreated: 2,
      billingCode: "180",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 8,
      patientId: "P008",
      patientLastName: "Moore",
      patientFirstName: "Sarah",
      patientMiddleName: "J",
      patientDOB: "06-18-1978",
      contactNumber: "555-890-1234",
      physicianName: "Dr. Patricia Davis",
      pg: "PG Gamma",
      hhah: "Comfort Care Services",
      patientInsurance: "Aetna",
      patientInEHR: "yes",
      patientSOC: "08-15-2024",
      patientEpisodeFrom: "08-15-2024",
      patientEpisodeTo: "10-14-2024",
      renderingPractitioner: "Dr. Daniel Wilson",
      primaryDiagnosisCodes: ["M17.9", "E11.9"],
      secondaryDiagnosisCodes: ["I10", "E78.5"],
      certStatus: "Document Signed",
      certSignedDate: "08-20-2024",
      recertStatus: "Not applicable",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Knee replacement recovery",
      cpoMinsCaptured: 75,
      newDocs: 4,
      newCpoDocsCreated: 1,
      billingCode: "181",
      charges: 113,
      pos: "11",
      units: 1
    },
    {
      id: 9,
      patientId: "P009",
      patientLastName: "Taylor",
      patientFirstName: "James",
      patientMiddleName: "R",
      patientDOB: "02-14-1952",
      contactNumber: "555-901-2345",
      physicianName: "Dr. Michael Johnson",
      pg: "PG Delta",
      hhah: "Elite Home Health",
      patientInsurance: "UnitedHealthcare",
      patientInEHR: "yes",
      patientSOC: "09-20-2024",
      patientEpisodeFrom: "09-20-2024",
      patientEpisodeTo: "11-19-2024",
      renderingPractitioner: "Dr. Lisa Anderson",
      primaryDiagnosisCodes: ["I48.91", "I10"],
      secondaryDiagnosisCodes: ["E78.5", "M54.2"],
      certStatus: "Document Prepared",
      certSignedDate: "",
      recertStatus: "Not applicable",
      recertSignedDate: "",
      f2fEligibility: "yes",
      patientRemarks: "Atrial fibrillation monitoring",
      cpoMinsCaptured: 100,
      newDocs: 6,
      newCpoDocsCreated: 2,
      billingCode: "179",
      charges: 113,
      pos: "11",
      units: 1
    }
  ]);

  const addPatient = (newPatient) => {
    setPatients(prevPatients => [...prevPatients, { ...newPatient, id: prevPatients.length + 1 }]);
  };

  const getPatientsByPG = (pgName) => {
    return patients.filter(patient => patient.pg === pgName);
  };

  return (
    <PatientContext.Provider value={{ patients, addPatient, getPatientsByPG }}>
      {children}
    </PatientContext.Provider>
  );
};

export const usePatientContext = () => {
  const context = useContext(PatientContext);
  if (!context) {
    throw new Error('usePatientContext must be used within a PatientProvider');
  }
  return context;
}; 