/**
 * Mapping of the regions to the 4 divisional groups
 */

export const regionToDivisionalGroup = {
  West: "West",
  Central: "Central",
  "East Central": "East Central",
  East: "East",
};

// Map each divisional group to its regions
export const divisionalGroupToRegions = {
  West: ["West"],
  Central: ["Central"],
  "East Central": ["East Central"],
  East: ["East"],
};

// Map each divisional group to its subdivisions from the map
export const divisionalGroupToSubdivisions = {
  West: [
    "Pacific Northwest Division",
    "Intermountain Division",
    "Southwest Division",
    "LA CA Division",
    "Bay Area Central CA Division"
  ],
  Central: [
    "Great Plains Division",
    "Illinois Wisconsin Division",
    "Central Division 3",
    "The South Division",
    "Central & East Texas Division"
  ],
  "East Central": [
    "East Central Divisional GRP Division 1",
    "East Central Divisional GRP Division 2",
    "East Central Divisional GRP Division 3",
    "East Central Divisional GRP Division 4",
    "East Central Divisional GRP Division 5"
  ],
  East: [
    "NEMA Divisional GRP Division 1",
    "NEMA Divisional GRP Division 2",
    "NEMA Divisional GRP Division 3",
    "NEMA Divisional GRP Division 4",
    "NEMA Divisional GRP Division 5"
  ]
};

// Subdivision colors based on the map
export const subdivisionColors = {
  "Pacific Northwest Division": "#FF5B76",
  "Intermountain Division": "#FF9A8B",
  "Southwest Division": "#FF6C5C",
  "LA CA Division": "#CC0000",
  "Bay Area Central CA Division": "#FFBDB4",
  "Great Plains Division": "#FFF7AA",
  "Illinois Wisconsin Division": "#FFBB8B",
  "Central Division 3": "#FFFF00",
  "The South Division": "#bfab97",
  "Central & East Texas Division": "#F0F0DC",
  "East Central Divisional GRP Division 1": "#73FADE",
  "East Central Divisional GRP Division 2": "#50CCA7",
  "East Central Divisional GRP Division 3": "#157F67",
  "East Central Divisional GRP Division 4": "#0b4e3e",
  "East Central Divisional GRP Division 5": "#a0e6a0",
  "NEMA Divisional GRP Division 1": "#702080",
  "NEMA Divisional GRP Division 2": "#8e44ad",
  "NEMA Divisional GRP Division 3": "#9966CC",
  "NEMA Divisional GRP Division 4": "#6a0dad",
  "NEMA Divisional GRP Division 5": "#d8bfd8"
};

// Map subdivisions to their MSAs based on geographical location
export const subdivisionToMSAs = {
  "Pacific Northwest Division": [
    "Seattle-Tacoma-Bellevue",
    "Portland-Vancouver-Hillsboro",
    "Bremerton-Silverdale",
    "Olympia-Tumwater",
    "Bellingham",
    "Mount Vernon-Anacortes",
    "Wenatchee",
    "Yakima",
    "Kennewick-Richland",
    "Spokane-Spokane Valley",
    "Walla Walla",
    "Anchorage",
    "Fairbanks",
    "Urban Honolulu",
    "Kahului-Wailuku-Lahaina"
  ],
  "Intermountain Division": [
    "Boise City",
    "Coeur d'Alene",
    "Idaho Falls",
    "Pocatello",
    "Twin Falls",
    "Billings",
    "Great Falls",
    "Missoula",
    "Cheyenne",
    "Casper",
    "Salt Lake City",
    "Ogden-Clearfield",
    "Provo-Orem",
    "St. George",
    "Logan",
    "Denver-Aurora-Lakewood",
    "Colorado Springs",
    "Fort Collins",
    "Boulder",
    "Greeley",
    "Grand Junction",
    "Pueblo"
  ],
  "Southwest Division": [
    "Phoenix-Mesa-Scottsdale",
    "Tucson",
    "Prescott",
    "Flagstaff",
    "Yuma",
    "Lake Havasu City-Kingman",
    "Sierra Vista-Douglas",
    "Albuquerque",
    "Las Cruces",
    "Santa Fe",
    "Farmington",
    "El Paso",
    "Lubbock",
    "Amarillo",
    "Midland",
    "Odessa"
  ],
  "LA CA Division": [
    "Los Angeles-Long Beach-Anaheim",
    "Riverside-San Bernardino-Ontario",
    "San Diego-Carlsbad",
    "Oxnard-Thousand Oaks-Ventura",
    "Bakersfield",
    "El Centro"
  ],
  "Bay Area Central CA Division": [
    "San Francisco-Oakland-Hayward",
    "San Jose-Sunnyvale-Santa Clara",
    "Sacramento-Roseville-Arden-Arcade",
    "Stockton-Lodi",
    "Modesto",
    "Fresno",
    "Visalia-Porterville",
    "Salinas",
    "Santa Cruz-Watsonville",
    "San Luis Obispo-Paso Robles-Arroyo Grande",
    "Santa Barbara",
    "Santa Maria-Santa Barbara",
    "Napa",
    "Vallejo-Fairfield",
    "Santa Rosa",
    "Merced",
    "Madera",
    "Hanford-Corcoran",
    "Redding",
    "Chico",
    "Yuba City"
  ],
  
  "Great Plains Division": [
    "Minneapolis-St. Paul-Bloomington",
    "Duluth",
    "Rochester", 
    "Mankato-North Mankato",
    "St. Cloud",
    "Fargo",
    "Bismarck",
    "Grand Forks",
    "Sioux Falls",
    "Rapid City",
    "Omaha-Council Bluffs",
    "Lincoln",
    "Grand Island",
    "Des Moines-West Des Moines",
    "Cedar Rapids",
    "Iowa City",
    "Waterloo-Cedar Falls",
    "Ames",
    "Dubuque",
    "Kansas City",
    "Wichita",
    "Topeka",
    "Lawrence",
    "Manhattan"
  ],
  "Illinois Wisconsin Division": [
    "Chicago-Naperville-Elgin",
    "Milwaukee-Waukesha-West Allis",
    "Madison",
    "Green Bay",
    "Appleton",
    "Racine",
    "Oshkosh-Neenah",
    "Eau Claire",
    "La Crosse-Onalaska",
    "Fond du Lac",
    "Janesville-Beloit",
    "Rockford",
    "Peoria",
    "Springfield",
    "Champaign-Urbana",
    "Bloomington",
    "Decatur",
    "Kankakee",
    "Carbondale-Marion"
  ],
  "Central Division 3": [
    "Oklahoma City",
    "Tulsa",
    "Lawton",
    "Enid",
    "Springfield",
    "Columbia",
    "Jefferson City",
    "Joplin",
    "Cape Girardeau"
  ],
  "The South Division": [
    "Little Rock-North Little Rock-Conway",
    "Fayetteville-Springdale-Rogers",
    "Fort Smith",
    "Hot Springs",
    "Jonesboro",
    "Pine Bluff",
    "New Orleans-Metairie",
    "Baton Rouge",
    "Shreveport-Bossier City",
    "Lafayette",
    "Lake Charles",
    "Monroe",
    "Alexandria",
    "Hammond",
    "Houma-Thibodaux",
    "Jackson",
    "Gulfport-Biloxi-Pascagoula",
    "Hattiesburg",
    "Birmingham-Hoover",
    "Huntsville",
    "Mobile",
    "Montgomery",
    "Tuscaloosa",
    "Dothan",
    "Auburn-Opelika",
    "Florence-Muscle Shoals",
    "Gadsden",
    "Daphne-Fairhope-Foley",
    "Anniston-Oxford-Jacksonville"
  ],
  "Central & East Texas Division": [
    "Dallas-Fort Worth-Arlington",
    "Houston-The Woodlands-Sugar Land",
    "San Antonio-New Braunfels",
    "Austin-Round Rock",
    "McAllen-Edinburg-Mission",
    "El Paso",
    "Corpus Christi",
    "Killeen-Temple",
    "Brownsville-Harlingen",
    "Beaumont-Port Arthur",
    "Laredo",
    "Lubbock",
    "Amarillo",
    "Waco",
    "College Station-Bryan",
    "Wichita Falls",
    "Tyler",
    "Longview",
    "Abilene",
    "San Angelo",
    "Texarkana",
    "Victoria",
    "Sherman-Denison"
  ],

  "East Central Divisional GRP Division 1": [
    "Detroit-Warren-Dearborn",
    "Grand Rapids-Wyoming",
    "Lansing-East Lansing",
    "Flint",
    "Kalamazoo-Portage",
    "Ann Arbor",
    "Saginaw",
    "Muskegon",
    "Battle Creek",
    "Bay City",
    "Midland"
  ],
  "East Central Divisional GRP Division 2": [
    "Indianapolis-Carmel-Anderson",
    "Fort Wayne",
    "Evansville",
    "South Bend-Mishawaka",
    "Lafayette",
    "Bloomington",
    "Elkhart-Goshen",
    "Muncie",
    "Terre Haute",
    "Michigan City-La Porte",
    "Kokomo",
    "Columbus"
  ],
  "East Central Divisional GRP Division 3": [
    "Cincinnati",
    "Cleveland-Elyria",
    "Columbus",
    "Dayton",
    "Akron",
    "Toledo",
    "Youngstown-Warren-Boardman",
    "Canton-Massillon"
  ],
  "East Central Divisional GRP Division 4": [
    "Nashville-Davidson--Murfreesboro--Franklin",
    "Memphis",
    "Knoxville",
    "Chattanooga",
    "Clarksville",
    "Jackson",
    "Johnson City",
    "Kingsport-Bristol-Bristol"
  ],
  "East Central Divisional GRP Division 5": [
    "Atlanta-Sandy Springs-Roswell",
    "Miami-Fort Lauderdale-Pompano Beach",
    "Tampa-St. Petersburg-Clearwater",
    "Orlando-Kissimmee-Sanford",
    "Jacksonville",
    "Savannah",
    "Augusta-Richmond County",
    "Columbus",
    "Macon-Bibb County",
    "Athens-Clarke County",
    "Gainesville",
    "Tallahassee",
    "Pensacola-Ferry Pass-Brent",
    "Cape Coral-Fort Myers",
    "Lakeland-Winter Haven",
    "Deltona-Daytona Beach-Ormond Beach",
    "Palm Bay-Melbourne-Titusville",
    "North Port-Sarasota-Bradenton"
  ],

  "NEMA Divisional GRP Division 1": [
    "Boston-Cambridge-Newton",
    "Providence-Warwick",
    "Worcester",
    "Manchester-Nashua",
    "Portland-South Portland",
    "Bangor",
    "Burlington-South Burlington",
    "Lewiston-Auburn"
  ],
  "NEMA Divisional GRP Division 2": [
    "New York-Newark-Jersey City",
    "Bridgeport-Stamford-Norwalk",
    "New Haven-Milford",
    "Hartford-West Hartford-East Hartford",
    "Albany-Schenectady-Troy",
    "Syracuse",
    "Rochester",
    "Buffalo-Cheektowaga-Niagara Falls",
    "Trenton",
    "Atlantic City-Hammonton"
  ],
  "NEMA Divisional GRP Division 3": [
    "Washington-Arlington-Alexandria",
    "Baltimore-Columbia-Towson",
    "Virginia Beach-Norfolk-Newport News",
    "Richmond",
    "Harrisburg-Carlisle",
    "Lancaster",
    "York-Hanover",
    "Reading",
    "Allentown-Bethlehem-Easton",
    "Scranton--Wilkes-Barre--Hazleton"
  ],
  "NEMA Divisional GRP Division 4": [
    "Charlotte-Concord-Gastonia",
    "Raleigh",
    "Greensboro-High Point",
    "Winston-Salem",
    "Durham-Chapel Hill",
    "Asheville",
    "Wilmington",
    "Greenville",
    "Fayetteville"
  ],
  "NEMA Divisional GRP Division 5": [
    "Philadelphia-Camden-Wilmington",
    "Pittsburgh",
    "Charleston",
    "Huntington-Ashland",
    "Columbia",
    "Charleston-North Charleston",
    "Greenville-Anderson-Mauldin",
    "Spartanburg",
    "Myrtle Beach-Conway-North Myrtle Beach",
    "Hilton Head Island-Bluffton-Beaufort"
  ]
};

// Statistical Area names for each region
export const regionToStatisticalAreas = {
  West: [
    
      "Abilene",
      "Albuquerque",
      "Amarillo",
      "Anchorage",
      "Bakersfield",
      "Bellingham",
      "Billings",
      "Boise City",
      "Boulder",
      "Bremerton-Silverdale",
      "Broomfield",
      "Brownsville-Harlingen",
      "Carson City",
      "Casper",
      "Cheyenne",
      "Chicago–Naperville–Elgin",
      "Chico",
      "Cleveland–Elyria",
      "Clovis Micropolitan Statistical Area",
      "Coeur d'Alene",
      "Colorado Springs",
      "Corpus Christi",
      "Dallas–Fort Worth–Arlington",
      "Denver-Aurora-Lakewood",
      "El Centro",
      "El Paso",
      "Fairbanks",
      "Farmington",
      "Flagstaff",
      "Fort Collins",
      "Fort Morgan Micropolitan Statistical Area",
      "Fresno",
      "Grand Junction",
      "Great Falls",
      "Greeley",
      "Hanford-Corcoran",
      "Hot Springs",
      "Idaho Falls",
      "Jonesboro",
      "Kahului-Wailuku-Lahaina",
      "Kennewick-Richland",
      "Lake Havasu City-Kingman",
      "Laredo",
      "Las Cruces",
      "Las Vegas-Henderson-Paradise",
      "Levelland Micropolitan Statistical Area",
      "Lewiston",
      "Little Rock-North Little Rock-Conway",
      "Logan",
      "Longview",
      "Los Angeles-Long Beach-Anaheim",
      "Lubbock",
      "Madera",
      "McAllen-Edinburg-Mission",
      "Merced",
      "Midland",
      "Missoula",
      "Modesto",
      "Mount Vernon-Anacortes",
      "Napa",
      "New York–Newark–Jersey City",
      "Odessa",
      "Ogden-Clearfield",
      "Olympia-Tumwater",
      "Oxnard-Thousand Oaks-Ventura",
      "Pampa Micropolitan Statistical Area",
      "Phoenix-Mesa-Scottsdale",
      "Pine Bluff",
      "Pocatello",
      "Prescott",
      "Provo-Orem",
      "Pueblo",
      "Redding",
      "Reno",
      "Riverside-San Bernardino-Ontario",
      "Sacramento-Roseville-Arden-Arcade",
      "Salinas",
      "Salt Lake City",
      "San Angelo",
      "San Diego-Carlsbad",
      "San Francisco-Oakland-Hayward",
      "San Jose-Sunnyvale-Santa Clara",
      "San Luis Obispo-Paso Robles-Arroyo Grande",
      "Santa Barbara",
      "Santa Cruz-Watsonville",
      "Santa Fe",
      "Santa Maria-Santa Barbara",
      "Santa Rosa",
      "Seattle-Tacoma-Bellevue",
      "Sierra Vista-Douglas",
      "Spokane-Spokane Valley",
      "St. George",
      "Sterling Micropolitan Statistical Area",
      "Stockton-Lodi",
      "Tucson",
      "Twin Falls",
      "Urban Honolulu",
      "Vallejo-Fairfield",
      "Visalia-Porterville",
      "Walla Walla",
      "Wenatchee",
      "Yakima",
      "Yuba City",
      "Yuma"
    
  ],

  Central: [
    "Albany",
    "Alexandria",
    "Alice Micropolitan Statistical Area",
    "Ames",
    "Anniston-Oxford-Jacksonville",
    "Appleton",
    "Ardmore Micropolitan Statistical Area",
    "Ashtabula",
    "Auburn-Opelika",
    "Austin-Round Rock",
    "Baton Rouge",
    "Beaumont-Port Arthur",
    "Benavides Micropolitan Statistical Area",
    "Bend-Redmond",
    "Birmingham-Hoover",
    "Bismarck",
    "Bloomington",
    "Brownsville–Harlingen",
    "Brownwood Micropolitan Statistical Area",
    "Bryan-College Station",
    "Cape Girardeau",
    "Carbondale-Marion",
    "Carlsbad Micropolitan Statistical Area",
    "Casper",
    "Cedar Rapids",
    "Champaign-Urbana",
    "Chicago-Naperville-Elgin",
    "Cleveland",
    "Cleveland-Elyria",
    "Columbia",
    "Columbus",
    "Corpus Christi",
    "Corvallis",
    "Dallas-Fort Worth-Arlington",
    "Danville",
    "Daphne-Fairhope-Foley",
    "Davenport-Moline-Rock Island",
    "Decatur",
    "Del Rio Micropolitan Statistical Area",
    "Denver-Aurora-Lakewood",
    "Des Moines-West Des Moines",
    "Dothan",
    "Dubuque",
    "Duluth",
    "Durant Micropolitan Statistical Area",
    "Eagle Pass Micropolitan Statistical Area",
    "Eau Claire",
    "El Paso",
    "Enid",
    "Eugene",
    "Fargo",
    "Fayetteville-Springdale-Rogers",
    "Florence-Muscle Shoals",
    "Fond du Lac",
    "Fort Smith",
    "Fort Worth-Arlington",
    "Gadsden",
    "Grand Forks",
    "Grand Island",
    "Grants Pass",
    "Green Bay",
    "Gulfport-Biloxi-Pascagoula",
    "Hammond",
    "Hattiesburg",
    "Houma-Thibodaux",
    "Houston-The Woodlands-Sugar Land",
    "Huntsville Micropolitan Statistical Area",
    "Huntsville",
    "Iowa City",
    "Jackson",
    "Janesville-Beloit",
    "Jefferson City",
    "Joplin",
    "Kankakee",
    "Kansas City",
    "Kerrville Micropolitan Statistical Area",
    "Killeen-Temple",
    "La Crosse-Onalaska",
    "Lafayette-Opelousas-Morgan City Combined Statistical Area",
    "Lafayette",
    "Lake Charles",
    "Laredo",
    "Laredo Micropolitan Statistical Area",
    "Lawrence",
    "Lawton",
    "Lincoln",
    "Livingston Micropolitan Statistical Area",
    "Longview",
    "Los Angeles-Long Beach-Anaheim",
    "Lubbock",
    "Madison",
    "Manhattan",
    "Mankato-North Mankato",
    "McAllen-Edinburg-Mission",
    "Medford",
    "Memphis",
    "Milwaukee-Waukesha-West Allis",
    "Minneapolis-St. Paul-Bloomington",
    "Mobile",
    "Monroe",
    "Montgomery",
    "Nacogdoches Micropolitan Statistical Area",
    "Natchez Micropolitan Statistical Area",
    "New Orleans-Metairie",
    "Odessa",
    "Ogden-Clearfield",
    "Oklahoma City",
    "Omaha-Council Bluffs",
    "Oshkosh-Neenah",
    "Palestine Micropolitan Statistical Area",
    "Paris Micropolitan Statistical Area",
    "Peoria",
    "Philadelphia-Camden-Wilmington",
    "Pittsburgh",
    "Portland-Vancouver-Hillsboro",
    "Racine",
    "Rapid City",
    "Rochester",
    "Rockford",
    "Sacramento-Roseville-Arden-Arcade",
    "Salem",
    "Salt Lake City",
    "San Antonio-New Braunfels",
    "San Marcos",
    "Sarasota-Bradenton-Venice",
    "Sebastian-Vero Beach",
    "Sheboygan",
    "Sherman-Denison",
    "Shreveport-Bossier City",
    "Sioux City",
    "Sioux Falls",
    "Springfield",
    "St. Cloud",
    "St. George",
    "St. Joseph",
    "St. Louis",
    "Sweetwater Micropolitan Statistical Area",
    "Texarkana",
    "Topeka",
    "Tulsa",
    "Tuscaloosa",
    "Tyler",
    "Victoria",
    "Waco",
    "Waterloo-Cedar Falls",
    "Wausau",
    "Wichita Falls",
    "Youngstown-Warren-Boardman"
],

  "East Central": [
    
      "Akron",
      "Albany-Schenectady-Troy",
      "Albany",
      "Anderson",
      "Ann Arbor",
      "Asheville",
      "Athens-Clarke County",
      "Atlanta-Sandy Springs-Roswell",
      "Augusta-Richmond County",
      "Baltimore-Columbia-Towson",
      "Battle Creek",
      "Bay City",
      "Beckley",
      "Binghamton",
      "Birmingham-Hoover",
      "Bloomington",
      "Boston-Cambridge-Newton",
      "Bowling Green Micropolitan Statistical Area",
      "Bowling Green",
      "Brunswick",
      "Bryan-College Station",
      "Buffalo-Cheektowaga-Niagara Falls",
      "Canton-Massillon",
      "Cape Coral-Fort Myers",
      "Charleston",
      "Chattanooga",
      "Chicago-Naperville-Elgin",
      "Cincinnati",
      "Clarksville",
      "Cleveland-Elyria",
      "Cleveland",
      "Columbia",
      "Columbia Micropolitan Statistical Area",
      "Columbus",
      "Columbus",
      "Cookeville Micropolitan Statistical Area",
      "Crestview-Fort Walton Beach-Destin",
      "Dallas-Fort Worth-Arlington",
      "Dalton",
      "Danville",
      "Dayton",
      "Deltona-Daytona Beach-Ormond Beach",
      "Detroit-Warren-Dearborn",
      "Detroit-Warren-Flint",
      "Elizabethtown-Fort Knox",
      "Elkhart-Goshen",
      "Elmira",
      "Erie",
      "Evansville",
      "Flint",
      "Fort Wayne",
      "Gainesville",
      "Gainesville",
      "Glens Falls",
      "Grand Rapids-Wyoming",
      "Greensboro-High Point",
      "Hinesville",
      "Hohenwald",
      "Homosassa Springs",
      "Houston-The Woodlands-Sugar Land",
      "Huntington-Ashland",
      "Indianapolis-Carmel-Anderson",
      "Ithaca",
      "Jackson",
      "Jacksonville",
      "Johnson City",
      "Kalamazoo-Portage",
      "Killeen-Temple-Fort Hood",
      "Kingsport-Bristol-Bristol",
      "Knoxville",
      "Kokomo",
      "Lafayette",
      "Lafayette-West Lafayette",
      "Lakeland-Winter Haven",
      "Lansing-East Lansing",
      "Lawrenceburg",
      "Lawrenceburg Micropolitan Statistical Area",
      "Lexington-Fayette",
      "Lima",
      "Los Angeles-Long Beach-Anaheim",
      "Louisville/Jefferson County",
      "Macon",
      "Mansfield",
      "McAllen-Edinburg-Mission",
      "McMinnville Micropolitan Statistical Area",
      "Memphis",
      "Miami-Fort Lauderdale-Pompano Beach",
      "Michigan City-La Porte",
      "Midland",
      "Milwaukee-Waukesha-West Allis",
      "Minneapolis-St. Paul-Bloomington",
      "Monroe",
      "Morgantown",
      "Morristown",
      "Muncie Micropolitan Statistical Area",
      "Muncie",
      "Muskegon",
      "Naples-Immokalee-Marco Island",
      "Nashville-Davidson-Murfreesboro-Franklin",
      "New York-Newark-Jersey City",
      "Niles-Benton Harbor",
      "North Port-Sarasota-Bradenton",
      "Ocala",
      "Oklahoma City",
      "Orlando-Kissimmee-Sanford",
      "Owensboro",
      "Palm Bay-Melbourne-Titusville",
      "Panama City",
      "Parkersburg-Vienna",
      "Pensacola-Ferry Pass-Brent",
      "Philadelphia-Camden-Wilmington",
      "Pittsburgh",
      "Port St. Lucie",
      "Punta Gorda",
      "Richmond",
      "Richmond Micropolitan Statistical Area",
      "Rochester",
      "Rome",
      "Saginaw",
      "Salt Lake City",
      "San Antonio-New Braunfels",
      "San Diego–Chula Vista–Carlsbad",
      "Savannah",
      "Sebastian-Vero Beach",
      "Sebring",
      "Shelbyville Micropolitan Statistical Area",
      "South Bend-Mishawaka",
      "Springfield",
      "St. Louis",
      "Syracuse",
      "Tallahassee",
      "Tampa-St. Petersburg-Clearwater",
      "Terre Haute",
      "Texarkana",
      "The Villages",
      "Toledo",
      "Tullahoma-Manchester Micropolitan Statistical Area",
      "Tullahoma–Manchester",
      "Utica-Rome",
      "Valdosta",
      "Warner Robins",
      "Watertown-Fort Drum",
      "Weirton-Steubenville",
      "Wheeling",
      "Wichita Falls"
    
  ],

  East: [
    "Allentown-Bethlehem-Easton, PA-NJ",
    "Asheville, NC",
    "Atlantic City-Hammonton, NJ",
    "Bangor, ME",
    "Barnstable Town, MA",
    "Blacksburg-Christiansburg-Radford, VA",
    "Boston-Cambridge-Nashua, MA-NH",
    "Bridgeport-Stamford-Norwalk, CT",
    "Burlington, NC",
    "Burlington-South Burlington, VT",
    "Charleston-North Charleston, SC",
    "Charlotte-Concord-Gastonia, NC-SC",
    "Charlottesville, VA",
    "Columbia, SC",
    "Cumberland, MD-WV",
    "Danbury, CT",
    "Dover, DE",
    "Dover-Durham, NH-ME",
    "Durham-Chapel Hill, NC",
    "East Stroudsburg, PA",
    "Fayetteville, NC",
    "Florence, SC",
    "Gettysburg, PA",
    "Goldsboro, NC",
    "Greenville, NC",
    "Greenville-Anderson-Mauldin, SC",
    "Hagerstown-Martinsburg, MD-WV",
    "Harrisburg-Carlisle, PA",
    "Hartford-West Hartford-East Hartford, CT",
    "Hickory-Lenoir-Morganton, NC",
    "Hilton Head Island-Bluffton-Beaufort, SC",
    "Jacksonville, NC",
    "Johnstown, PA",
    "Lancaster, PA",
    "Lebanon, PA",
    "Leominster-Gardner, MA",
    "Lewiston-Auburn, ME",
    "Lynchburg, VA",
    "Manchester, NH",
    "Myrtle Beach-Conway-North Myrtle Beach, SC-NC",
    "New Bedford, MA",
    "New Haven, CT",
    "New Bern, NC",
    "New York-Newark-Jersey City, NY-NJ-PA",
    "Norwich-New London-Westerly, CT-RI",
    "Ocean City, NJ",
    "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",
    "Pittsfield, MA",
    "Portland-South Portland, ME",
    "Portsmouth, NH-ME",
    "Providence-Warwick, RI-MA",
    "Raleigh, NC",
    "Reading, PA",
    "Richmond, VA",
    "Roanoke, VA",
    "Rocky Mount, NC",
    "Salisbury, MD-DE",
    "Scranton--Wilkes-Barre--Hazleton, PA",
    "Spartanburg, SC",
    "Springfield, MA-CT",
    "Staunton-Waynesboro, VA",
    "State College, PA",
    "Sumter, SC",
    "Trenton, NJ",
    "Vineland-Bridgeton, NJ",
    "Virginia Beach-Norfolk-Newport News, VA-NC",
    "Washington-Arlington-Alexandria, DC-VA-MD-WV",
    "Waterbury, CT",
    "Wilmington, NC",
    "Williamsport, PA",
    "Winston-Salem, NC",
    "Worcester, MA-CT",
    "York-Hanover, PA",
    "Youngstown-Warren-Boardman, OH-PA",
  ],
};

// Statistics for each region (consolidated from previous regions)
export const regionStatistics = {
  West: {
    patients: 51230, // Sum of Pacific Northwest, Southwest, Northern California, Southern California, and Mountain divisions
    physicianGroups: 412,
    agencies: 178,
    activeOutcomes: 18670,
  },
  Central: {
    patients: 33120, // Sum of Southeast, South Central, Gulf Coast, Central Plains, and NEMA divisions
    physicianGroups: 276,
    agencies: 113,
    activeOutcomes: 9840,
  },
  "East Central": {
    patients: 38750, // Sum of Midwest 1&2, Great Lakes, Ohio Valley, and East Central divisions
    physicianGroups: 295,
    agencies: 124,
    activeOutcomes: 10250,
  },
  East: {
    patients: 42650, // Sum of Northeast 1&2, Atlantic, New England, and Mid-Atlantic divisions
    physicianGroups: 358,
    agencies: 147,
    activeOutcomes: 12330,
  },
};

// Sample statistics for each statistical area
export const statisticalAreaStatistics = {};

// Generate statistics for each statistical area
Object.entries(regionToStatisticalAreas).forEach(([region, areas]) => {
  const regionStats = regionStatistics[region];
  // Distribute the region's statistics among its statistical areas
  const areaCount = areas.length;

  areas.forEach((area, index) => {
    // Create slightly varied statistics for each area
    const variationFactor = 0.7 + Math.random() * 0.6; // Between 0.7 and 1.3

    statisticalAreaStatistics[area] = {
      patients: Math.round(
        (regionStats.patients / areaCount) * variationFactor
      ),
      physicianGroups: Math.round(
        (regionStats.physicianGroups / areaCount) * variationFactor
      ),
      agencies: Math.round(
        (regionStats.agencies / areaCount) * variationFactor
      ),
      activeOutcomes: Math.round(
        (regionStats.activeOutcomes / areaCount) * variationFactor
      ),
    };
  });
});

// Generate a direct mapping from divisional group to statistical areas
export const divisionalGroupToStatisticalAreas = {
  East: [],
  "East Central": [],
  West: [],
  Central: [],
};

// Populate the direct mapping
Object.entries(divisionalGroupToRegions).forEach(
  ([divisionalGroup, regions]) => {
    regions.forEach((region) => {
      const areas = regionToStatisticalAreas[region] || [];
      divisionalGroupToStatisticalAreas[divisionalGroup] = [
        ...divisionalGroupToStatisticalAreas[divisionalGroup],
        ...areas,
      ];
    });
  }
);

// Calculate statistics for each subdivision based on its MSAs
export const getSubdivisionStatistics = (subdivision) => {
  const msas = subdivisionToMSAs[subdivision] || [];
  
  // Initialize totals
  const stats = {
    patients: 0,
    physicianGroups: 0,
    agencies: 0,
    activeOutcomes: 0
  };
  
  // Sum up statistics for all MSAs in this subdivision
  msas.forEach(msa => {
    const msaStats = statisticalAreaStatistics[msa] || {};
    stats.patients += msaStats.patients || 0;
    stats.physicianGroups += msaStats.physicianGroups || 0;
    stats.agencies += msaStats.agencies || 0;
    stats.activeOutcomes += msaStats.activeOutcomes || 0;
  });
  
  return stats;
};

export default {
  regionToDivisionalGroup,
  divisionalGroupToRegions,
  regionToStatisticalAreas,
  divisionalGroupToStatisticalAreas,
  regionStatistics,
  statisticalAreaStatistics,
  getSubdivisionStatistics,
};
